### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [alejandrorodriguezarias/A-FIPA-ACL-based-communication-utility-forUnity#1]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by suprafun** [comment]
Hello, sorry to bother you. Just wanted to bump this. Thanks

**Comment by alejandrorodriguezarias** [comment]
Hello,

Sorry, I have not received the notification.

I have updated the repository with an MIT license.

My best
